// SkillSplore subject catalogue — a hierarchical taxonomy inspired by the depth of
// large services marketplaces (profi.ru lists ~1,900 tutoring subjects). This is
// a realistic starter catalogue; administrators can extend it at runtime.
//
// The 10 subjects named in the specification (Thermodynamics, Engineering
// mathematics, Programming, NCEA calculus, Saxophone, Piano, English, Russian,
// Vietnamese, SolidWorks) are all present so the demo tutors resolve correctly.

import { OTHER_SUBJECT_NAME } from '../src/lib/taxonomyConstants.js';
export { OTHER_SUBJECT_NAME };

export interface CategoryDef {
  name: string;
  icon: string; // emoji used on category tiles
  subjects: string[];
  // A handful of categories are shown on the homepage; everything else is
  // reached through search and the full browse page. Without this the
  // homepage would need to render three dozen tiles.
  featured?: boolean;
}

export const TAXONOMY: CategoryDef[] = [
  {
    name: 'Languages',
    icon: '🗣️',
    featured: true,
    subjects: [
      'English',
      'English as a second language',
      'Conversational English',
      'Academic English',
      'Business English',
      'English pronunciation',
      'IELTS preparation',
      'TOEFL preparation',
      'PTE preparation',
      'French',
      'Spanish',
      'German',
      'Italian',
      'Portuguese',
      'Mandarin Chinese',
      'Cantonese',
      'Japanese',
      'Korean',
      'Russian',
      'Ukrainian',
      'Vietnamese',
      'Thai',
      'Indonesian',
      'Arabic',
      'Hebrew',
      'Hindi',
      'Punjabi',
      'Tamil',
      'Turkish',
      'Greek',
      'Dutch',
      'Polish',
      'Persian or Farsi',
      'Latin',
      'Te Reo Māori',
      'New Zealand Sign Language',
      'Samoan',
      'Tongan',
      'Language exchange',
      'Accent reduction',
      'Translation skills',
      'Interpreting skills',
    ],
  },
  {
    name: 'Mathematics',
    icon: '➗',
    featured: true,
    subjects: [
      'Primary maths',
      'NCEA calculus',
      'NCEA statistics',
      'Algebra',
      'Geometry',
      'Trigonometry',
      'Calculus',
      'Engineering mathematics',
      'University mathematics',
    ],
  },
  {
    name: 'Sciences',
    icon: '🔬',
    subjects: [
      'Physics',
      'Chemistry',
      'Biology',
      'Thermodynamics',
      'Earth & space science',
      'Environmental science',
      'Anatomy & physiology',
    ],
  },
  {
    name: 'English & Humanities',
    icon: '📚',
    subjects: [
      'English literature',
      'Essay & academic writing',
      'History',
      'Geography',
      'Classical studies',
      'Philosophy',
      'Media studies',
    ],
  },
  {
    name: 'Computer Science & IT',
    icon: '💻',
    featured: true,
    subjects: [
      'Programming',
      'Python',
      'JavaScript',
      'Web development',
      'Java',
      'C++',
      'Data science',
      'Machine learning',
      'Databases & SQL',
      'Cybersecurity',
      'Game development',
    ],
  },
  {
    name: 'Engineering & CAD',
    icon: '📐',
    subjects: [
      'SolidWorks',
      'AutoCAD',
      'Fusion 360',
      'MATLAB',
      'Mechanical engineering',
      'Electrical engineering',
      'Civil engineering',
    ],
  },
  {
    name: 'Music',
    icon: '🎵',
    featured: true,
    subjects: [
      'Piano',
      'Guitar',
      'Violin',
      'Cello',
      'Saxophone',
      'Flute',
      'Drums',
      'Ukulele',
      'Singing & vocals',
      'Music theory',
      'Music production',
    ],
  },
  {
    name: 'Exam & Test Prep',
    icon: '📝',
    subjects: [
      'NCEA exam preparation',
      'University Entrance',
      'Scholarship exams',
      'SAT preparation',
      'GRE preparation',
      'GMAT preparation',
      'Cambridge exams',
    ],
  },
  {
    name: 'Business & Economics',
    icon: '📈',
    featured: true,
    subjects: [
      'Accounting',
      'Economics',
      'Business studies',
      'Finance',
      'Marketing',
      'Statistics for business',
    ],
  },
  {
    name: 'Arts & Design',
    icon: '🎨',
    featured: true,
    subjects: [
      'Drawing',
      'Painting',
      'Graphic design',
      'Photography',
      'Digital art',
      'Art history',
    ],
  },
  {
    name: 'Professional Skills',
    icon: '🧑‍💼',
    subjects: [
      'Microsoft Excel',
      'Public speaking',
      'CV & resume writing',
      'Interview preparation',
      'Project management',
    ],
  },
  {
    name: 'Sports & Fitness',
    icon: '⚽',
    featured: true,
    subjects: [
      'Personal training',
      'Yoga',
      'Swimming coaching',
      'Tennis coaching',
      'Football coaching',
      'Basketball coaching',
      'Rugby coaching',
      'Golf coaching',
      'Running & athletics',
    ],
  },
  {
    name: 'Cooking & Culinary Skills',
    icon: '🍳',
    featured: true,
    subjects: [
      'Cooking fundamentals',
      'Baking',
      'Cake decorating',
      'Meal prep',
      'Vegan & vegetarian cooking',
      'International cuisine',
    ],
  },
  {
    name: 'Beauty & Personal Care',
    icon: '💄',
    subjects: [
      'Makeup application',
      'Special occasion & bridal makeup',
      'Skincare basics',
      'Facials & skin treatments',
      'Hairstyling basics',
      'Hair colouring',
      'Barbering',
      'Nail care basics',
      'Nail art',
      'Lash extensions',
      'Brow shaping & tinting',
      'Waxing & hair removal',
      'Beauty therapy fundamentals',
      'Personal grooming',
    ],
  },
  {
    // Note: cosmetic tattooing is a licensed activity in New Zealand and
    // Australia. Listed here as something to learn about.
    name: 'Tattoo & Permanent Makeup',
    icon: '🖋️',
    subjects: [
      'Tattoo design & flash',
      'Tattoo aftercare',
      'Cosmetic tattooing',
      'Microblading',
      'Lip blush & powder brows',
      'Henna & temporary body art',
    ],
  },
  {
    name: 'Writing & Content',
    icon: '✍️',
    subjects: [
      'Creative writing',
      'Copywriting',
      'Blogging & content writing',
      'Journalism basics',
      'Freelance writing',
    ],
  },
  {
    name: 'Trades & Practical Skills',
    icon: '🔧',
    featured: true,
    subjects: [
      'Basic plumbing skills',
      'Basic electrical skills',
      'Woodworking basics',
      'DIY home repair',
      'Gardening & landscaping basics',
    ],
  },
  {
    name: 'Performing Arts & Dance',
    icon: '🎭',
    subjects: [
      'Dance',
      'Acting & drama',
      'Improv',
      'Voice coaching',
    ],
  },
  {
    // Taught as craft, tradition and interest.
    name: 'Esoteric & Spiritual Practice',
    icon: '🔮',
    subjects: [
      'Tarot reading',
      'Astrology',
      'Witchcraft & folk traditions',
      'Crystals & stones',
      'Numerology',
      'Runes & divination',
      'Herbalism & plant lore',
      'Meditation & mindfulness',
      'Dream interpretation',
    ],
  },
  {
    name: 'Crafts & Handmade',
    icon: '🧵',
    subjects: [
      'Knitting',
      'Crochet',
      'Sewing & dressmaking',
      'Embroidery',
      'Pottery & ceramics',
      'Jewellery making',
      'Candle & soap making',
      'Calligraphy & lettering',
      'Bookbinding',
      'Leatherwork',
    ],
  },
  {
    name: 'Games & Strategy',
    icon: '♟️',
    subjects: [
      'Chess',
      'Poker strategy',
      'Esports coaching',
      'Game design',
      'Tabletop roleplaying',
      'Board game strategy',
    ],
  },
  {
    name: 'Animals & Pets',
    icon: '🐕',
    subjects: [
      'Dog training',
      'Puppy basics',
      'Pet grooming',
      'Horse riding',
      'Animal care & husbandry',
      'Beekeeping',
    ],
  },
  {
    name: 'Outdoors & Nature',
    icon: '🏕️',
    subjects: [
      'Bushcraft & survival',
      'Foraging',
      'Fishing',
      'Hiking & navigation',
      'Camping skills',
      'Birdwatching',
      'Astronomy & stargazing',
    ],
  },
  {
    name: 'Home & Living',
    icon: '🏠',
    subjects: [
      'Interior design',
      'Home organisation & decluttering',
      'Personal budgeting',
      'Bike maintenance',
      'Sustainable living',
      'Furniture assembly',
      'Painting & decorating',
      'Basic tiling',
      'Basic plastering',
      'Cleaning skills',
      'Laundry & clothing care',
      'Renovation planning',
      'Moving-house planning',
      'Flatting & shared-house skills',
    ],
  },

  // --- New categories -------------------------------------------------------
  // Everything below is additive: existing categories and subjects above are
  // untouched, since syncTaxonomy.ts only ever inserts what is missing and a
  // renamed or removed entry here would not rename or remove the live row --
  // it would leave the old one in place and add a duplicate alongside it.

  {
    name: 'Data, AI & Automation',
    icon: '🤖',
    featured: true,
    subjects: [
      'Data analysis',
      'Data visualisation',
      'Data cleaning',
      'Data literacy',
      'Database design',
      'SQL for data analysis',
      'Power BI',
      'Tableau',
      'Looker Studio',
      'Statistical analysis',
      'R for data science',
      'Python for data science',
      'Deep learning',
      'Neural networks',
      'Natural language processing',
      'Computer vision',
      'Large language models',
      'Generative artificial intelligence',
      'Prompt engineering',
      'AI agent development',
      'AI for business',
      'AI for education',
      'Workflow automation',
      'Zapier',
      'Make.com',
      'n8n',
      'Data engineering',
      'Business intelligence',
      'Forecasting',
      'A/B testing',
    ],
  },
  {
    name: 'Cybersecurity, Cloud & IT',
    icon: '🔐',
    subjects: [
      'Cybersecurity fundamentals',
      'Digital privacy',
      'Password security',
      'Network fundamentals',
      'Network security',
      'Ethical hacking fundamentals',
      'Security awareness',
      'Linux administration',
      'Windows administration',
      'Server administration',
      'IT support',
      'Help-desk skills',
      'Cloud computing',
      'Amazon Web Services',
      'Microsoft Azure',
      'Google Cloud Platform',
      'Docker',
      'Kubernetes',
      'DevOps fundamentals',
      'Infrastructure as code',
      'Website hosting',
      'Domain & DNS management',
      'Home-network setup',
      'Computer hardware',
      'PC building',
      'Computer repair',
      'Data backup',
    ],
  },
  {
    name: 'Career & Workplace Development',
    icon: '🧑‍💼',
    featured: true,
    subjects: [
      'Career planning',
      'Career change guidance',
      'Job searching',
      'CV writing',
      'Cover-letter writing',
      'LinkedIn profile development',
      'Behavioural interview practice',
      'Graduate-job preparation',
      'Salary negotiation',
      'Workplace confidence',
      'Professional email writing',
      'Meeting skills',
      'Remote-work skills',
      'Office administration',
      'Leadership development',
      'People management',
      'Team building',
      'Conflict resolution',
      'Coaching skills',
      'Mentoring skills',
      'Human resources fundamentals',
      'Recruitment fundamentals',
      'Workplace productivity',
      'Networking skills',
      'Professional etiquette',
      'Freelance career development',
      'Portfolio development',
    ],
  },
  {
    name: 'Sales & Marketing',
    icon: '📣',
    subjects: [
      'Sales fundamentals',
      'Retail sales',
      'B2B sales',
      'Sales prospecting',
      'Objection handling',
      'Closing sales',
      'Customer service',
      'Negotiation skills',
      'Digital marketing',
      'Marketing strategy',
      'Social media marketing',
      'Content marketing',
      'Email marketing',
      'Search engine optimisation',
      'Search engine marketing',
      'Google Ads',
      'Meta advertising',
      'LinkedIn marketing',
      'TikTok marketing',
      'Influencer marketing',
      'Community management',
      'Public relations',
      'Brand strategy',
      'Personal branding',
      'Marketing analytics',
      'Conversion optimisation',
      'Copywriting for marketing',
    ],
  },
  {
    name: 'Personal Development & Wellbeing',
    icon: '🌱',
    subjects: [
      'Goal setting',
      'Habit building',
      'Personal organisation',
      'Time management',
      'Productivity',
      'Confidence building',
      'Social confidence',
      'Conversation skills',
      'Emotional awareness',
      'Stress-management education',
      'Mindfulness',
      'Meditation',
      'Journalling',
      'Resilience building',
      'Motivation coaching',
      'Decision making',
      'Critical thinking',
      'Memory improvement',
      'Speed reading',
      'Boundary-setting education',
      'Sleep-habit education',
      'Digital wellbeing',
    ],
  },
  {
    name: 'Parenting & Family Learning',
    icon: '👪',
    subjects: [
      'Parenting fundamentals',
      'Positive parenting',
      'Positive discipline',
      'Child-development education',
      'School readiness',
      'Early literacy',
      'Early numeracy',
      'Reading with children',
      'Homework support',
      'Homeschooling support',
      'Learning through play',
      'Teen study skills',
      'Youth mentoring',
      'Gifted-learning support',
      'Babysitting skills',
      'Childcare fundamentals',
      'Family technology safety',
    ],
  },
  {
    name: 'Learning Accessibility & Support',
    icon: '🧩',
    subjects: [
      'Adult literacy',
      'Adult numeracy',
      'Digital literacy',
      'Dyslexia-friendly learning strategies',
      'ADHD-friendly study strategies',
      'Autism-friendly learning approaches',
      'Executive-function support',
      'Sensory-friendly instruction',
      'Assistive technology',
      'Screen-reader use',
      'Speech-to-text tools',
      'Text-to-speech tools',
      'Accessible document creation',
      'Study support for mature learners',
      'One-to-one supported learning',
    ],
  },
  {
    name: 'Civic, Consumer & Legal Literacy',
    icon: '⚖️',
    subjects: [
      'New Zealand civics',
      'Australian civics',
      'Voting & government basics',
      'Consumer-rights education',
      'Tenancy basics',
      'Employment-rights basics',
      'Contract fundamentals',
      'Small-business compliance basics',
      'Privacy fundamentals',
      'Intellectual-property fundamentals',
      'Copyright fundamentals',
      'Immigration-process literacy',
      'Mediation fundamentals',
      'Dispute-resolution education',
      'Understanding official documents',
    ],
  },
  {
    name: 'Safety & Emergency Preparedness',
    icon: '🚑',
    subjects: [
      'First aid',
      'CPR',
      'Child first aid',
      'Workplace first aid',
      'Workplace safety',
      'Fire safety',
      'Food safety',
      'Road safety',
      'Water safety',
      'Outdoor safety',
      'Emergency preparedness',
      'Disaster preparedness',
      'Home safety',
      'Personal safety',
      'Self-defence',
      'Conflict de-escalation',
      'Scam & fraud awareness',
      'Child online safety',
    ],
  },
  {
    name: 'Automotive & Transport',
    icon: '🚗',
    subjects: [
      'Driving lessons',
      'Learner-licence preparation',
      'Restricted-licence preparation',
      'Full-licence preparation',
      'Defensive driving',
      'Manual-transmission driving',
      'Parking practice',
      'Motorway driving',
      'Trailer reversing',
      'Motorcycle riding fundamentals',
      'Bicycle riding',
      'Bicycle maintenance',
      'Car-maintenance basics',
      'Tyre & battery care',
      'Automotive detailing',
      'Used-car buying guidance',
      'Drone piloting',
    ],
  },
  {
    name: 'Photography, Video & Content Creation',
    icon: '📷',
    featured: true,
    subjects: [
      'Photography fundamentals',
      'Smartphone photography',
      'Portrait photography',
      'Street photography',
      'Landscape photography',
      'Product photography',
      'Event photography',
      'Studio lighting',
      'Photo composition',
      'Adobe Lightroom',
      'Photo editing & retouching',
      'Videography',
      'Cinematography basics',
      'Video lighting',
      'Video editing',
      'Adobe Premiere Pro',
      'DaVinci Resolve',
      'Final Cut Pro',
      'After Effects',
      'Motion graphics',
      'Animation basics',
      'Documentary filmmaking',
      'Podcasting',
      'Podcast editing',
      'YouTube content creation',
      'TikTok content creation',
      'Instagram Reels',
      'Livestreaming',
      'Content planning & strategy',
      'On-camera confidence',
    ],
  },
  {
    name: 'Gardening & Sustainable Living',
    icon: '🌿',
    subjects: [
      'Gardening fundamentals',
      'Vegetable gardening',
      'Herb gardening',
      'Fruit-tree care',
      'Flower gardening',
      'Native plants',
      'Indoor plant care',
      'Houseplant care',
      'Bonsai',
      'Seed starting',
      'Plant propagation',
      'Pruning',
      'Soil health',
      'Composting',
      'Worm farming',
      'Lawn care',
      'Garden design',
      'Landscaping fundamentals',
      'Permaculture',
      'Organic gardening',
      'Chicken keeping',
      'Waste reduction & recycling',
      'Home energy efficiency',
      'Water conservation',
    ],
  },
  {
    // Deliberately not featured: this exists purely as the FK target for
    // TutoringRequest.subjectId when a poster chose "Other subject or skill"
    // and typed something that isn't in the catalogue yet -- see
    // OTHER_SUBJECT_NAME below and requests.routes.ts. What they actually
    // typed is stored in customSubjectLabel and shown instead of this name.
    name: 'Other / Not Yet Listed',
    icon: '❓',
    subjects: [OTHER_SUBJECT_NAME],
  },
];

// Convenience: total number of subjects in the catalogue.
export const TOTAL_SUBJECTS = TAXONOMY.reduce((n, c) => n + c.subjects.length, 0);

/**
 * Search aliases: a term a learner might actually type, mapped to the
 * catalogue entry it should resolve to. Search treats an alias hit as
 * equivalent to a direct name match against the target category or subject.
 *
 * `target` is looked up by exact subject name first, then by category name --
 * subject and category names are both globally unique, so this is unambiguous.
 * Keep the left-hand term short and colloquial; the taxonomy above already
 * has the formal name.
 */
export interface AliasDef {
  term: string;
  target: string;
}

export const ALIASES: AliasDef[] = [
  { term: 'maths', target: 'Mathematics' },
  { term: 'math', target: 'Mathematics' },
  { term: 'coding', target: 'Programming' },
  { term: 'programing', target: 'Programming' },
  { term: 'code', target: 'Programming' },
  { term: 'piano lessons', target: 'Piano' },
  { term: 'art classes', target: 'Drawing' },
  { term: 'art class', target: 'Painting' },
  { term: 'public speaking coach', target: 'Public speaking' },
  { term: 'english tutor', target: 'English' },
  { term: 'esl', target: 'English as a second language' },
  { term: 'ai', target: 'Generative artificial intelligence' },
  { term: 'chatgpt', target: 'Generative artificial intelligence' },
  { term: 'gpt', target: 'Generative artificial intelligence' },
  { term: 'ml', target: 'Machine learning' },
  { term: 'js', target: 'JavaScript' },
  { term: 'ts', target: 'JavaScript' },
  { term: 'web dev', target: 'Web development' },
  { term: 'webdev', target: 'Web development' },
  { term: 'seo', target: 'Search engine optimisation' },
  { term: 'cyber security', target: 'Cybersecurity fundamentals' },
  { term: 'cybersecurity', target: 'Cybersecurity, Cloud & IT' },
  { term: 'excel', target: 'Microsoft Excel' },
  { term: 'photoshop', target: 'Digital art' },
  { term: 'resume', target: 'CV & resume writing' },
  { term: 'cv writing', target: 'CV & resume writing' },
  { term: 'job interview', target: 'Interview preparation' },
  { term: 'first aid course', target: 'First aid' },
  { term: 'cpr training', target: 'CPR' },
  { term: 'driving lessons', target: 'Driving lessons' },
  { term: 'learners licence', target: 'Learner-licence preparation' },
  { term: 'restricted licence', target: 'Restricted-licence preparation' },
  { term: 'car maintenance', target: 'Car-maintenance basics' },
  { term: 'gym', target: 'Personal training' },
  { term: 'pt', target: 'Personal training' },
  { term: 'weightlifting', target: 'Personal training' },
  { term: 'football', target: 'Football coaching' },
  { term: 'soccer', target: 'Football coaching' },
  { term: 'baking classes', target: 'Baking' },
  { term: 'makeup artist', target: 'Makeup application' },
  { term: 'mua', target: 'Makeup application' },
  { term: 'hairdressing', target: 'Hairstyling basics' },
  { term: 'hairdresser', target: 'Hairstyling basics' },
  { term: 'nails', target: 'Nail art' },
  { term: 'tattooist', target: 'Tattoo design & flash' },
  { term: 'permanent makeup', target: 'Cosmetic tattooing' },
  { term: 'pmu', target: 'Cosmetic tattooing' },
  { term: 'tarot', target: 'Tarot reading' },
  { term: 'witch', target: 'Witchcraft & folk traditions' },
  { term: 'wicca', target: 'Witchcraft & folk traditions' },
  { term: 'knitting lessons', target: 'Knitting' },
  { term: 'sewing lessons', target: 'Sewing & dressmaking' },
  { term: 'pottery classes', target: 'Pottery & ceramics' },
  { term: 'chess coach', target: 'Chess' },
  { term: 'dog training', target: 'Dog training' },
  { term: 'puppy training', target: 'Puppy basics' },
  { term: 'plumber', target: 'Basic plumbing skills' },
  { term: 'electrician', target: 'Basic electrical skills' },
  { term: 'handyman', target: 'DIY home repair' },
  { term: 'gardening', target: 'Gardening & Sustainable Living' },
  { term: 'garden', target: 'Gardening fundamentals' },
  { term: 'yoga classes', target: 'Yoga' },
  { term: 'meditation classes', target: 'Meditation' },
  { term: 'mindfulness training', target: 'Mindfulness' },
  { term: 'counselling', target: 'Personal Development & Wellbeing' },
  { term: 'life coach', target: 'Personal Development & Wellbeing' },
  { term: 'business coach', target: 'Business & Economics' },
  { term: 'accounting tutor', target: 'Accounting' },
  { term: 'bookkeeping', target: 'Accounting' },
  { term: 'photography classes', target: 'Photography fundamentals' },
  { term: 'photo editing', target: 'Photo editing & retouching' },
  { term: 'video editing classes', target: 'Video editing' },
  { term: 'youtube', target: 'YouTube content creation' },
  { term: 'tiktok', target: 'TikTok content creation' },
  { term: 'podcast', target: 'Podcasting' },
  { term: 'drama classes', target: 'Acting & drama' },
  { term: 'singing lessons', target: 'Singing & vocals' },
  { term: 'vocal coach', target: 'Singing & vocals' },
  { term: 'dance classes', target: 'Dance' },
  { term: 'ballet', target: 'Dance' },
  { term: 'guitar lessons', target: 'Guitar' },
  { term: 'drum lessons', target: 'Drums' },
  { term: 'music production classes', target: 'Music production' },
  { term: 'beekeeper', target: 'Beekeeping' },
  { term: 'composting', target: 'Composting' },
  { term: 'stargazing', target: 'Astronomy & stargazing' },
  { term: 'astronomy', target: 'Astronomy & stargazing' },
  { term: 'hiking', target: 'Hiking & navigation' },
  { term: 'tramping', target: 'Hiking & navigation' },
  { term: 'camping', target: 'Camping skills' },
  { term: 'survival skills', target: 'Bushcraft & survival' },
  { term: 'foraging', target: 'Foraging' },
  { term: 'te reo', target: 'Te Reo Māori' },
  { term: 'maori language', target: 'Te Reo Māori' },
  { term: 'nz sign language', target: 'New Zealand Sign Language' },
  { term: 'auslan', target: 'New Zealand Sign Language' },
  { term: 'esports', target: 'Esports coaching' },
  { term: 'gaming coach', target: 'Esports coaching' },
  { term: 'dungeons and dragons', target: 'Tabletop roleplaying' },
  { term: 'dnd', target: 'Tabletop roleplaying' },
];
