// SkillSplore subject catalogue — a hierarchical taxonomy inspired by the depth of
// large services marketplaces (profi.ru lists ~1,900 tutoring subjects). This is
// a realistic starter catalogue; administrators can extend it at runtime.
//
// The 10 subjects named in the specification (Thermodynamics, Engineering
// mathematics, Programming, NCEA calculus, Saxophone, Piano, English, Russian,
// Vietnamese, SolidWorks) are all present so the demo tutors resolve correctly.

export interface CategoryDef {
  name: string;
  icon: string; // emoji used on category tiles
  subjects: string[];
}

export const TAXONOMY: CategoryDef[] = [
  {
    name: 'Languages',
    icon: '🗣️',
    subjects: [
      'English',
      'English as a second language',
      'IELTS preparation',
      'TOEFL preparation',
      'French',
      'Spanish',
      'German',
      'Mandarin Chinese',
      'Japanese',
      'Korean',
      'Russian',
      'Vietnamese',
      'Italian',
      'Arabic',
      'Te Reo Māori',
    ],
  },
  {
    name: 'Mathematics',
    icon: '➗',
    subjects: [
      'Primary maths',
      'NCEA calculus',
      'NCEA statistics',
      'Algebra',
      'Geometry',
      'Trigonometry',
      'Calculus',
      'Engineering mathematics',
      'University mathematics',
    ],
  },
  {
    name: 'Sciences',
    icon: '🔬',
    subjects: [
      'Physics',
      'Chemistry',
      'Biology',
      'Thermodynamics',
      'Earth & space science',
      'Environmental science',
      'Anatomy & physiology',
    ],
  },
  {
    name: 'English & Humanities',
    icon: '📚',
    subjects: [
      'English literature',
      'Essay & academic writing',
      'History',
      'Geography',
      'Classical studies',
      'Philosophy',
      'Media studies',
    ],
  },
  {
    name: 'Computer Science & IT',
    icon: '💻',
    subjects: [
      'Programming',
      'Python',
      'JavaScript',
      'Web development',
      'Java',
      'C++',
      'Data science',
      'Machine learning',
      'Databases & SQL',
      'Cybersecurity',
      'Game development',
    ],
  },
  {
    name: 'Engineering & CAD',
    icon: '📐',
    subjects: [
      'SolidWorks',
      'AutoCAD',
      'Fusion 360',
      'MATLAB',
      'Mechanical engineering',
      'Electrical engineering',
      'Civil engineering',
    ],
  },
  {
    name: 'Music',
    icon: '🎵',
    subjects: [
      'Piano',
      'Guitar',
      'Violin',
      'Cello',
      'Saxophone',
      'Flute',
      'Drums',
      'Ukulele',
      'Singing & vocals',
      'Music theory',
      'Music production',
    ],
  },
  {
    name: 'Exam & Test Prep',
    icon: '📝',
    subjects: [
      'NCEA exam preparation',
      'University Entrance',
      'Scholarship exams',
      'SAT preparation',
      'GRE preparation',
      'GMAT preparation',
      'Cambridge exams',
    ],
  },
  {
    name: 'Business & Economics',
    icon: '📈',
    subjects: [
      'Accounting',
      'Economics',
      'Business studies',
      'Finance',
      'Marketing',
      'Statistics for business',
    ],
  },
  {
    name: 'Arts & Design',
    icon: '🎨',
    subjects: [
      'Drawing',
      'Painting',
      'Graphic design',
      'Photography',
      'Digital art',
      'Art history',
    ],
  },
  {
    name: 'Professional Skills',
    icon: '🧑‍💼',
    subjects: [
      'Microsoft Excel',
      'Public speaking',
      'CV & resume writing',
      'Interview preparation',
      'Project management',
    ],
  },
  {
    name: 'Sports & Fitness',
    icon: '⚽',
    subjects: [
      'Personal training',
      'Yoga',
      'Swimming coaching',
      'Tennis coaching',
      'Football coaching',
      'Basketball coaching',
      'Rugby coaching',
      'Golf coaching',
      'Running & athletics',
    ],
  },
  {
    name: 'Cooking & Culinary Skills',
    icon: '🍳',
    subjects: [
      'Cooking fundamentals',
      'Baking',
      'Cake decorating',
      'Meal prep',
      'Vegan & vegetarian cooking',
      'International cuisine',
    ],
  },
  {
    name: 'Beauty & Personal Care',
    icon: '💄',
    subjects: [
      'Makeup application',
      'Special occasion & bridal makeup',
      'Skincare basics',
      'Facials & skin treatments',
      'Hairstyling basics',
      'Hair colouring',
      'Barbering',
      'Nail care basics',
      'Nail art',
      'Lash extensions',
      'Brow shaping & tinting',
      'Waxing & hair removal',
      'Beauty therapy fundamentals',
      'Personal grooming',
    ],
  },
  {
    // Note: cosmetic tattooing is a licensed activity in New Zealand and
    // Australia. Listed here as something to learn about.
    name: 'Tattoo & Permanent Makeup',
    icon: '🖋️',
    subjects: [
      'Tattoo design & flash',
      'Tattoo aftercare',
      'Cosmetic tattooing',
      'Microblading',
      'Lip blush & powder brows',
      'Henna & temporary body art',
    ],
  },
  {
    name: 'Writing & Content',
    icon: '✍️',
    subjects: [
      'Creative writing',
      'Copywriting',
      'Blogging & content writing',
      'Journalism basics',
      'Freelance writing',
    ],
  },
  {
    name: 'Trades & Practical Skills',
    icon: '🔧',
    subjects: [
      'Basic plumbing skills',
      'Basic electrical skills',
      'Woodworking basics',
      'DIY home repair',
      'Gardening & landscaping basics',
    ],
  },
  {
    name: 'Performing Arts & Dance',
    icon: '🎭',
    subjects: [
      'Dance',
      'Acting & drama',
      'Improv',
      'Voice coaching',
    ],
  },
  {
    // Taught as craft, tradition and interest.
    name: 'Esoteric & Spiritual Practice',
    icon: '🔮',
    subjects: [
      'Tarot reading',
      'Astrology',
      'Witchcraft & folk traditions',
      'Crystals & stones',
      'Numerology',
      'Runes & divination',
      'Herbalism & plant lore',
      'Meditation & mindfulness',
      'Dream interpretation',
    ],
  },
  {
    name: 'Crafts & Handmade',
    icon: '🧵',
    subjects: [
      'Knitting',
      'Crochet',
      'Sewing & dressmaking',
      'Embroidery',
      'Pottery & ceramics',
      'Jewellery making',
      'Candle & soap making',
      'Calligraphy & lettering',
      'Bookbinding',
      'Leatherwork',
    ],
  },
  {
    name: 'Games & Strategy',
    icon: '♟️',
    subjects: [
      'Chess',
      'Poker strategy',
      'Esports coaching',
      'Game design',
      'Tabletop roleplaying',
      'Board game strategy',
    ],
  },
  {
    name: 'Animals & Pets',
    icon: '🐕',
    subjects: [
      'Dog training',
      'Puppy basics',
      'Pet grooming',
      'Horse riding',
      'Animal care & husbandry',
      'Beekeeping',
    ],
  },
  {
    name: 'Outdoors & Nature',
    icon: '🏕️',
    subjects: [
      'Bushcraft & survival',
      'Foraging',
      'Fishing',
      'Hiking & navigation',
      'Camping skills',
      'Birdwatching',
      'Astronomy & stargazing',
    ],
  },
  {
    name: 'Home & Living',
    icon: '🏠',
    subjects: [
      'Interior design',
      'Home organisation & decluttering',
      'Personal budgeting',
      'Car maintenance basics',
      'Bike maintenance',
      'Sustainable living',
    ],
  },
];

// Convenience: total number of subjects in the catalogue.
export const TOTAL_SUBJECTS = TAXONOMY.reduce((n, c) => n + c.subjects.length, 0);
